/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProsesPemasran;

import ProsesTeknik.*;
import ProsesLab.*;
import KomponenGUI.FDateF;
import LSubProces.DRunSelctOne;
import LSubProces.Insert;
import LSubProces.Update;
import LSubProces.UpdateAll;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static GlobalVar.Var.*;

/**
 *
 * @author Gudang Garam
 */
public class PengaduanPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form PengujianBahanBaku
     */
    String IdEdit;

    public PengaduanPelanggan() {
        initComponents();
        setVisible(true);
        setTitle("Tambah Pengaduan Pelanggan");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jbuttonF3.setVisible(false);
        JTAsalInstitusi.requestFocus();
    }

    public PengaduanPelanggan(Object idEdit) {
        IdEdit = idEdit.toString();
        initComponents();
        setVisible(true);
        setTitle("Ubah Pengaduan Pelanggan");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jbuttonF1.setVisible(false);
        jbuttonF2.setVisible(false);
        loadEditData();
        JTAsalInstitusi.requestFocus();
    }

    void loadEditData() {
        DRunSelctOne dRunSelctOne = new DRunSelctOne();
        dRunSelctOne.setQuery("SELECT `IdPengaduan` as 'ID', DATE_FORMAT(`Tanggal`,'%d-%m-%Y') as 'Tanggal', `AsalInstitusi` as 'Asal/Institusi', `YangMenerima` as 'Yang Menerima', `JenisPengaduan` as 'Jenis Pengaduan', `BagianYangMenangani` as 'Bagian Yang Menangani', `RincianPengaduan` as 'Rincian Pengaduan', `TindakLanjutPengaduan` as 'Tindak Lanjut Pengaduan', `TindakanPencegahan` as 'Tindakan Pencegahan', DATE_FORMAT(`TargetTanggalPenyelesaian`,'%d-%m-%Y') as 'Target Tanggal Penyesuaian', `VerifikasiPenyelesaian` as 'Verifikasi Penyelesaian', IF(`Selesai`=1,'Selesai','Belum Selesai') as 'Status' FROM `snitbpengaduanpelanggan` WHERE `IdPengaduan` = " + IdEdit);
        ArrayList<String> list = dRunSelctOne.excute();
        JDTanggalPengaduan.setDate(FDateF.strtodate(list.get(1), "dd-MM-yyyy"));
        JTAsalInstitusi.setText(list.get(2));
        JTYangMenerima.setText(list.get(3));
        JCJenisPengaduan.setSelectedItem(list.get(4));
        JCBagianYangMenangani.setSelectedItem(list.get(5));
        JTARincianPengaduan.setText(list.get(6));
        JTATindakLanjut.setText(list.get(7));
        JTATindakanPencegahan.setText(list.get(8));
        JDTanggalTargetPenyelesaian.setDate(FDateF.strtodate(list.get(9), "dd-MM-yyyy"));
        JTVerifikasiPenyelesaian.setText(list.get(10));
        JCBSelesai.setSelected(list.get(11).equals("Selesai"));
    }

    Boolean checkInput() {
        if (JDTanggalPengaduan.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Tanggal Pengaduan Tidak Boleh Kosong");
            return false;
        } else if (JTAsalInstitusi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Asal / Institusi Tidak Boleh Kosong");
            return false;
        } else if (JTYangMenerima.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Yang Menerima Tidak Boleh Kosong");
            return false;
        } else if (JDTanggalTargetPenyelesaian.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Tanggal Target Penyelesaian Tidak Boleh Kosong");
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbuttonF1 = new KomponenGUI.JbuttonF();
        jbuttonF2 = new KomponenGUI.JbuttonF();
        jbuttonF4 = new KomponenGUI.JbuttonF();
        jbuttonF3 = new KomponenGUI.JbuttonF();
        JDTanggalPengaduan = new KomponenGUI.JdateCF();
        jlableF23 = new KomponenGUI.JlableF();
        jlableF24 = new KomponenGUI.JlableF();
        jlableF6 = new KomponenGUI.JlableF();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTARincianPengaduan = new KomponenGUI.JTextAreaF();
        jlableF8 = new KomponenGUI.JlableF();
        jlableF34 = new KomponenGUI.JlableF();
        jlableF9 = new KomponenGUI.JlableF();
        jlableF35 = new KomponenGUI.JlableF();
        JTAsalInstitusi = new KomponenGUI.JtextF();
        jlableF10 = new KomponenGUI.JlableF();
        jlableF36 = new KomponenGUI.JlableF();
        JTYangMenerima = new KomponenGUI.JtextF();
        JLNetto4 = new KomponenGUI.JlableF();
        JLNetto5 = new KomponenGUI.JlableF();
        JCBSelesai = new KomponenGUI.JCheckBoxF();
        JCJenisPengaduan = new KomponenGUI.JcomboboxF();
        JLNetto6 = new KomponenGUI.JlableF();
        JLNetto7 = new KomponenGUI.JlableF();
        JCBagianYangMenangani = new KomponenGUI.JcomboboxF();
        JLNetto8 = new KomponenGUI.JlableF();
        JLNetto9 = new KomponenGUI.JlableF();
        jlableF7 = new KomponenGUI.JlableF();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTATindakLanjut = new KomponenGUI.JTextAreaF();
        JLNetto10 = new KomponenGUI.JlableF();
        jlableF11 = new KomponenGUI.JlableF();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTATindakanPencegahan = new KomponenGUI.JTextAreaF();
        JDTanggalTargetPenyelesaian = new KomponenGUI.JdateCF();
        jlableF25 = new KomponenGUI.JlableF();
        jlableF26 = new KomponenGUI.JlableF();
        JTVerifikasiPenyelesaian = new KomponenGUI.JtextF();
        jlableF37 = new KomponenGUI.JlableF();
        jlableF12 = new KomponenGUI.JlableF();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jbuttonF1.setText("Tambah");
        jbuttonF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF1ActionPerformed(evt);
            }
        });

        jbuttonF2.setText("Tambah & Tutup");
        jbuttonF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF2ActionPerformed(evt);
            }
        });

        jbuttonF4.setText("Kembali");
        jbuttonF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF4ActionPerformed(evt);
            }
        });

        jbuttonF3.setText("Ubah");
        jbuttonF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF3ActionPerformed(evt);
            }
        });

        JDTanggalPengaduan.setDate(new Date());
        JDTanggalPengaduan.setDateFormatString("dd-MM-yyyy");
        JDTanggalPengaduan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JDTanggalPengaduanPropertyChange(evt);
            }
        });
        JDTanggalPengaduan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JDTanggalPengaduanKeyPressed(evt);
            }
        });

        jlableF23.setText("Tgl Pengaduan");

        jlableF24.setText(":");

        jlableF6.setText(":");

        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane1KeyPressed(evt);
            }
        });

        JTARincianPengaduan.setColumns(20);
        JTARincianPengaduan.setRows(5);
        JTARincianPengaduan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTARincianPengaduanKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(JTARincianPengaduan);

        jlableF8.setText("Status");

        jlableF34.setText(":");

        jlableF9.setText("Asal / Institusi");

        jlableF35.setText(":");

        JTAsalInstitusi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTAsalInstitusiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTAsalInstitusiKeyReleased(evt);
            }
        });

        jlableF10.setText("Yang Menerima");

        jlableF36.setText(":");

        JTYangMenerima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTYangMenerimaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTYangMenerimaKeyReleased(evt);
            }
        });

        JLNetto4.setText(":");

        JLNetto5.setText("Jenis Pengaduan");

        JCBSelesai.setSelected(false);
        JCBSelesai.setText("Selesai");
        JCBSelesai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JCBSelesaiKeyPressed(evt);
            }
        });

        JCJenisPengaduan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biasa" }));
        JCJenisPengaduan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JCJenisPengaduanKeyPressed(evt);
            }
        });

        JLNetto6.setText("Bagian Yang Menangani");

        JLNetto7.setText(":");

        JCBagianYangMenangani.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gudang" }));
        JCBagianYangMenangani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JCBagianYangMenanganiKeyPressed(evt);
            }
        });

        JLNetto8.setText("Rincian Pengaduan");

        JLNetto9.setText("Tindak Lanjut");

        jlableF7.setText(":");

        jScrollPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane2KeyPressed(evt);
            }
        });

        JTATindakLanjut.setColumns(20);
        JTATindakLanjut.setRows(5);
        JTATindakLanjut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTATindakLanjutKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(JTATindakLanjut);

        JLNetto10.setText("Tindakan Pencegahan");

        jlableF11.setText(":");

        jScrollPane3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane3KeyPressed(evt);
            }
        });

        JTATindakanPencegahan.setColumns(20);
        JTATindakanPencegahan.setRows(5);
        JTATindakanPencegahan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTATindakanPencegahanKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(JTATindakanPencegahan);

        JDTanggalTargetPenyelesaian.setDate(new Date());
        JDTanggalTargetPenyelesaian.setDateFormatString("dd-MM-yyyy");
        JDTanggalTargetPenyelesaian.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JDTanggalTargetPenyelesaianPropertyChange(evt);
            }
        });
        JDTanggalTargetPenyelesaian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JDTanggalTargetPenyelesaianKeyPressed(evt);
            }
        });

        jlableF25.setText("Target Penyelesaian");

        jlableF26.setText(":");

        JTVerifikasiPenyelesaian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTVerifikasiPenyelesaianKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTVerifikasiPenyelesaianKeyReleased(evt);
            }
        });

        jlableF37.setText(":");

        jlableF12.setText("Verifikasi Penyelesaian");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbuttonF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlableF8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlableF12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlableF25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLNetto10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLNetto9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLNetto8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLNetto6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLNetto5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlableF10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlableF9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlableF23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JLNetto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JCBagianYangMenangani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlableF26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JDTanggalTargetPenyelesaian, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JLNetto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JCJenisPengaduan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlableF11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlableF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlableF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlableF24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JDTanggalPengaduan, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlableF35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTAsalInstitusi, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlableF36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTYangMenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlableF37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTVerifikasiPenyelesaian, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlableF34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JCBSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlableF23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlableF24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JDTanggalPengaduan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlableF35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTAsalInstitusi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlableF36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTYangMenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNetto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNetto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCJenisPengaduan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNetto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNetto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBagianYangMenangani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLNetto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlableF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlableF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLNetto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlableF11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLNetto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JDTanggalTargetPenyelesaian, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlableF26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlableF25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlableF37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTVerifikasiPenyelesaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlableF34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF1ActionPerformed
        tambahData(false);
    }//GEN-LAST:event_jbuttonF1ActionPerformed

    private void jbuttonF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF2ActionPerformed
        tambahData(true);
    }//GEN-LAST:event_jbuttonF2ActionPerformed

    private void jbuttonF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF4ActionPerformed
        dispose();
    }//GEN-LAST:event_jbuttonF4ActionPerformed

    private void jbuttonF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF3ActionPerformed
        ubahData();
    }//GEN-LAST:event_jbuttonF3ActionPerformed

    private void JDTanggalPengaduanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JDTanggalPengaduanPropertyChange

    }//GEN-LAST:event_JDTanggalPengaduanPropertyChange

    private void JDTanggalPengaduanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JDTanggalPengaduanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JTARincianPengaduan.requestFocus();
        }
    }//GEN-LAST:event_JDTanggalPengaduanKeyPressed

    private void JTARincianPengaduanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTARincianPengaduanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JTATindakLanjut.requestFocus();
        }
    }//GEN-LAST:event_JTARincianPengaduanKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (IdEdit == null) {
            tambahPengaduanPelanggan = null;
        } else {
            ubahPengaduanPelanggan = null;
        }
    }//GEN-LAST:event_formWindowClosed

    private void jScrollPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jbuttonF1.isVisible()) {
                tambahData(false);
            } else {
                ubahData();
            }
        }
    }//GEN-LAST:event_jScrollPane1KeyPressed

    private void JTAsalInstitusiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTAsalInstitusiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JTYangMenerima.requestFocus();
        }
    }//GEN-LAST:event_JTAsalInstitusiKeyPressed

    private void JTAsalInstitusiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTAsalInstitusiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JTAsalInstitusiKeyReleased

    private void JTYangMenerimaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTYangMenerimaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JCJenisPengaduan.requestFocus();
        }
    }//GEN-LAST:event_JTYangMenerimaKeyPressed

    private void JTYangMenerimaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTYangMenerimaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JTYangMenerimaKeyReleased

    private void JTATindakLanjutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTATindakLanjutKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JTATindakanPencegahan.requestFocus();
        }
    }//GEN-LAST:event_JTATindakLanjutKeyPressed

    private void jScrollPane2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2KeyPressed

    private void JTATindakanPencegahanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTATindakanPencegahanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JTVerifikasiPenyelesaian.requestFocus();
        }
    }//GEN-LAST:event_JTATindakanPencegahanKeyPressed

    private void jScrollPane3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3KeyPressed

    private void JDTanggalTargetPenyelesaianPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JDTanggalTargetPenyelesaianPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_JDTanggalTargetPenyelesaianPropertyChange

    private void JDTanggalTargetPenyelesaianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JDTanggalTargetPenyelesaianKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JDTanggalTargetPenyelesaianKeyPressed

    private void JTVerifikasiPenyelesaianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTVerifikasiPenyelesaianKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JCBSelesai.requestFocus();
        }
    }//GEN-LAST:event_JTVerifikasiPenyelesaianKeyPressed

    private void JTVerifikasiPenyelesaianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTVerifikasiPenyelesaianKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JTVerifikasiPenyelesaianKeyReleased

    private void JCJenisPengaduanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCJenisPengaduanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JCBagianYangMenangani.requestFocus();
        }
    }//GEN-LAST:event_JCJenisPengaduanKeyPressed

    private void JCBagianYangMenanganiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCBagianYangMenanganiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JTARincianPengaduan.requestFocus();
        }
    }//GEN-LAST:event_JCBagianYangMenanganiKeyPressed

    private void JCBSelesaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCBSelesaiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jbuttonF1.isVisible()) {
                tambahData(false);
            } else {
                ubahData();
            }
        }
    }//GEN-LAST:event_JCBSelesaiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengaduanPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengaduanPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengaduanPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengaduanPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengaduanPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private KomponenGUI.JCheckBoxF JCBSelesai;
    private KomponenGUI.JcomboboxF JCBagianYangMenangani;
    private KomponenGUI.JcomboboxF JCJenisPengaduan;
    private static KomponenGUI.JdateCF JDTanggalPengaduan;
    private static KomponenGUI.JdateCF JDTanggalTargetPenyelesaian;
    private KomponenGUI.JlableF JLNetto10;
    private KomponenGUI.JlableF JLNetto4;
    private KomponenGUI.JlableF JLNetto5;
    private KomponenGUI.JlableF JLNetto6;
    private KomponenGUI.JlableF JLNetto7;
    private KomponenGUI.JlableF JLNetto8;
    private KomponenGUI.JlableF JLNetto9;
    private KomponenGUI.JTextAreaF JTARincianPengaduan;
    private KomponenGUI.JTextAreaF JTATindakLanjut;
    private KomponenGUI.JTextAreaF JTATindakanPencegahan;
    private KomponenGUI.JtextF JTAsalInstitusi;
    private KomponenGUI.JtextF JTVerifikasiPenyelesaian;
    private KomponenGUI.JtextF JTYangMenerima;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private KomponenGUI.JbuttonF jbuttonF1;
    private KomponenGUI.JbuttonF jbuttonF2;
    private KomponenGUI.JbuttonF jbuttonF3;
    private KomponenGUI.JbuttonF jbuttonF4;
    private KomponenGUI.JlableF jlableF10;
    private KomponenGUI.JlableF jlableF11;
    private KomponenGUI.JlableF jlableF12;
    private KomponenGUI.JlableF jlableF23;
    private KomponenGUI.JlableF jlableF24;
    private KomponenGUI.JlableF jlableF25;
    private KomponenGUI.JlableF jlableF26;
    private KomponenGUI.JlableF jlableF34;
    private KomponenGUI.JlableF jlableF35;
    private KomponenGUI.JlableF jlableF36;
    private KomponenGUI.JlableF jlableF37;
    private KomponenGUI.JlableF jlableF6;
    private KomponenGUI.JlableF jlableF7;
    private KomponenGUI.JlableF jlableF8;
    private KomponenGUI.JlableF jlableF9;
    // End of variables declaration//GEN-END:variables

    void tambahData(Boolean tutup) {
        if (checkInput()) {
            Insert insert = new Insert();
            Boolean berhasil = false;
            berhasil = insert.simpan("INSERT INTO `snitbpengaduanpelanggan`(`Tanggal`, `AsalInstitusi`, `YangMenerima`, `JenisPengaduan`, `BagianYangMenangani`, `RincianPengaduan`, `TindakLanjutPengaduan`, `TindakanPencegahan`, `TargetTanggalPenyelesaian`, `VerifikasiPenyelesaian`, `Selesai`) VALUES ('" + FDateF.datetostr(JDTanggalPengaduan.getDate(), "yyyy-MM-dd") + "','" + JTAsalInstitusi.getText() + "','" + JTYangMenerima.getText() + "','" + JCJenisPengaduan.getSelectedItem() + "','" + JCBagianYangMenangani.getSelectedItem() + "','" + JTARincianPengaduan.getText() + "','" + JTATindakLanjut.getText() + "','" + JTATindakanPencegahan.getText() + "','" + FDateF.datetostr(JDTanggalTargetPenyelesaian.getDate(), "yyyy-MM-dd") + "','" + JTVerifikasiPenyelesaian.getText() + "'," + JCBSelesai.isSelected() + ")", "Pengaduan Pelanggan", this);
            if (berhasil) {
                if (listPengaduanPelanggan != null) {
                    listPengaduanPelanggan.load();
                }
                if (tutup) {
                    tambahPengaduanPelanggan.dispose();
                    tambahPengaduanPelanggan = null;
                } else {
                    JTAsalInstitusi.setText("");
                    JTYangMenerima.setText("");
                    JTARincianPengaduan.setText("");
                    JTATindakLanjut.setText("");
                    JTATindakanPencegahan.setText("");
                    JTVerifikasiPenyelesaian.setText("");
                    JTAsalInstitusi.requestFocus();
                }
            }
        }
    }

    void ubahData() {
        if (checkInput()) {
            Update update = new Update();
            Boolean berhasil = false;
            berhasil = update.Ubah("UPDATE `snitbpengaduanpelanggan` SET `Tanggal`='" + FDateF.datetostr(JDTanggalPengaduan.getDate(), "yyyy-MM-dd") + "',`AsalInstitusi`='" + JTAsalInstitusi.getText() + "',`YangMenerima`='" + JTYangMenerima.getText() + "',`JenisPengaduan`='" + JCJenisPengaduan.getSelectedItem() + "',`BagianYangMenangani`='" + JCBagianYangMenangani.getSelectedItem() + "',`RincianPengaduan`='" + JTARincianPengaduan.getText() + "',`TindakLanjutPengaduan`='" + JTATindakLanjut.getText() + "',`TindakanPencegahan`='" + JTATindakanPencegahan.getText() + "',`TargetTanggalPenyelesaian`='" + FDateF.datetostr(JDTanggalTargetPenyelesaian.getDate(), "yyyy-MM-dd") + "',`VerifikasiPenyelesaian`='" + JTVerifikasiPenyelesaian.getText() + "',`Selesai`=" + JCBSelesai.isSelected() + " WHERE `IdPengaduan` = " + IdEdit, "Pengaduan Pelanggan", this);
            if (listPengaduanPelanggan != null) {
                listPengaduanPelanggan.load();
            }
            if (berhasil) {
                dispose();
            }
        }
    }

}
