/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProsesPemasran;

import ProsesLab.*;
import KomponenGUI.FDateF;
import LSubProces.DRunSelctOne;
import LSubProces.Insert;
import LSubProces.Update;
import LSubProces.UpdateAll;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static GlobalVar.Var.*;

/**
 *
 * @author Gudang Garam
 */
public class SurveyKepuasanPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form PengujianBahanBaku
     */
    String IdEdit;

    public SurveyKepuasanPelanggan() {
        initComponents();
        setVisible(true);
        setTitle("Tambah Survey Kepuasan Pelanggan");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jbuttonF3.setVisible(false);
    }

    public SurveyKepuasanPelanggan(Object idEdit) {
        IdEdit = idEdit.toString();
        initComponents();
        setVisible(true);
        setTitle("Ubah Survey Kepuasan Pelanggan");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jbuttonF1.setVisible(false);
        jbuttonF2.setVisible(false);
        loadEditData();
    }

    void loadEditData() {
        DRunSelctOne dRunSelctOne = new DRunSelctOne();
        dRunSelctOne.setQuery("SELECT `IdSurveyKepuasanPelanggan` as 'ID', `NamaPerusahaan` as 'Nama Perusahaan', `Alamat`, DATE_FORMAT(`Tanggal`,'%d-%m-%Y') as 'Tanggal', `NamaPelanggan` as 'Nama Pelanggan', `Nilai`, `CatatanDariPelanggan` as 'Catatan Dari Pelanggan' FROM `snitbsurveykepuasanpelanggan` WHERE `IdSurveyKepuasanPelanggan` = " + IdEdit);
        ArrayList<String> list = dRunSelctOne.excute();
        JTNamaPerusahaan.setText(list.get(1));
        JTAlamat.setText(list.get(2));
        JDTanggal.setDate(FDateF.strtodate(list.get(3), "dd-MM-yyyy"));
        JTNamaPelanggan.setText(list.get(4));
        jNumberOnly1.setText(list.get(5).split("\\,")[0]);
        jNumberOnly2.setText(list.get(5).split("\\,")[1]);
        jNumberOnly3.setText(list.get(5).split("\\,")[2]);
        jNumberOnly4.setText(list.get(5).split("\\,")[3]);
        jNumberOnly5.setText(list.get(5).split("\\,")[4]);
        jNumberOnly6.setText(list.get(5).split("\\,")[5]);
        jNumberOnly7.setText(list.get(5).split("\\,")[6]);
        jNumberOnly8.setText(list.get(5).split("\\,")[7]);
        jNumberOnly9.setText(list.get(5).split("\\,")[8]);
        JTACatatanPelanggan.setText(list.get(6));
    }

    Boolean checkInput() {
        if (JDTanggal.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Tanggal Terima Tidak Boleh Kosong");
            return false;
        } else if (JTNamaPelanggan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Warna Tidak Boleh Kosong");
            return false;
        } else {
            return true;
        }
    }

    String getNilai() {
        return jNumberOnly1.getText() + "," + jNumberOnly2.getText() + "," + jNumberOnly3.getText() + "," + jNumberOnly4.getText() + "," + jNumberOnly5.getText() + "," + jNumberOnly6.getText() + "," + jNumberOnly7.getText() + "," + jNumberOnly8.getText() + "," + jNumberOnly9.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbuttonF1 = new KomponenGUI.JbuttonF();
        jbuttonF2 = new KomponenGUI.JbuttonF();
        jbuttonF4 = new KomponenGUI.JbuttonF();
        jbuttonF3 = new KomponenGUI.JbuttonF();
        JDTanggal = new KomponenGUI.JdateCF();
        jlableF23 = new KomponenGUI.JlableF();
        jlableF24 = new KomponenGUI.JlableF();
        jlableF6 = new KomponenGUI.JlableF();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTACatatanPelanggan = new KomponenGUI.JTextAreaF();
        jlableF7 = new KomponenGUI.JlableF();
        jlableF33 = new KomponenGUI.JlableF();
        JTNamaPelanggan = new KomponenGUI.JtextF();
        jlableF8 = new KomponenGUI.JlableF();
        jlableF34 = new KomponenGUI.JlableF();
        jlableF9 = new KomponenGUI.JlableF();
        jlableF35 = new KomponenGUI.JlableF();
        JTNamaPerusahaan = new KomponenGUI.JtextF();
        jlableF10 = new KomponenGUI.JlableF();
        jlableF36 = new KomponenGUI.JlableF();
        JTAlamat = new KomponenGUI.JtextF();
        jlableF11 = new KomponenGUI.JlableF();
        jlableF12 = new KomponenGUI.JlableF();
        jlableF13 = new KomponenGUI.JlableF();
        jlableF14 = new KomponenGUI.JlableF();
        jlableF15 = new KomponenGUI.JlableF();
        jlableF16 = new KomponenGUI.JlableF();
        jlableF17 = new KomponenGUI.JlableF();
        jlableF18 = new KomponenGUI.JlableF();
        jlableF19 = new KomponenGUI.JlableF();
        jNumberOnly1 = new KomponenGUI.JNumberOnly();
        jNumberOnly2 = new KomponenGUI.JNumberOnly();
        jNumberOnly3 = new KomponenGUI.JNumberOnly();
        jNumberOnly4 = new KomponenGUI.JNumberOnly();
        jNumberOnly5 = new KomponenGUI.JNumberOnly();
        jNumberOnly6 = new KomponenGUI.JNumberOnly();
        jNumberOnly7 = new KomponenGUI.JNumberOnly();
        jNumberOnly8 = new KomponenGUI.JNumberOnly();
        jNumberOnly9 = new KomponenGUI.JNumberOnly();
        jlableF20 = new KomponenGUI.JlableF();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jbuttonF1.setText("Tambah");
        jbuttonF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF1ActionPerformed(evt);
            }
        });

        jbuttonF2.setText("Tambah & Tutup");
        jbuttonF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF2ActionPerformed(evt);
            }
        });

        jbuttonF4.setText("Kembali");
        jbuttonF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF4ActionPerformed(evt);
            }
        });

        jbuttonF3.setText("Ubah");
        jbuttonF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF3ActionPerformed(evt);
            }
        });

        JDTanggal.setDate(new Date());
        JDTanggal.setDateFormatString("dd-MM-yyyy");
        JDTanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JDTanggalPropertyChange(evt);
            }
        });
        JDTanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JDTanggalKeyPressed(evt);
            }
        });

        jlableF23.setText("Tanggal");

        jlableF24.setText(":");

        jlableF6.setText(":");

        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane1KeyPressed(evt);
            }
        });

        JTACatatanPelanggan.setColumns(20);
        JTACatatanPelanggan.setRows(5);
        JTACatatanPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTACatatanPelangganKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(JTACatatanPelanggan);

        jlableF7.setText("Nama Pelanggan");

        jlableF33.setText(":");

        JTNamaPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTNamaPelangganKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTNamaPelangganKeyReleased(evt);
            }
        });

        jlableF8.setText("Pertanyaan");

        jlableF34.setText(":");

        jlableF9.setText("Nama Perusahaan");

        jlableF35.setText(":");

        JTNamaPerusahaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTNamaPerusahaanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTNamaPerusahaanKeyReleased(evt);
            }
        });

        jlableF10.setText("Alamat");

        jlableF36.setText(":");

        JTAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTAlamatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTAlamatKeyReleased(evt);
            }
        });

        jlableF11.setText("1. Pelaksanaan Pemenuhan Sesuai Pesanan");
        jlableF11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlableF12.setText("2. Kerja dan Hubungan Interaktif antara Perusahaan dengan Pelanggan");
        jlableF12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlableF13.setText("3. Kebersihan Gudang dan Kantor Pemasaran");
        jlableF13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlableF14.setText("4. Pemenuhan Persyaratan Pelanggan / Spesifikasi");
        jlableF14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlableF15.setText("5. Ketepatan Waktu Pengiriman Produk");
        jlableF15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlableF16.setText("6. Penerapan Sistem Manajemen Mutu Dan Pelayanan Pelanggan Di Perusahaan");
        jlableF16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlableF17.setText("7. Sistem Proses Produksi Yang Telah Dilakukan Perusahaan (Mutu Produk)");
        jlableF17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlableF18.setText("8. Respon Perusahaan Terhadap Keluhan Pelanggan");
        jlableF18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlableF19.setText("9. Kelengkapan Dokumen Yang Diperlukan Pelanggan");
        jlableF19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jNumberOnly1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNumberOnly1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jNumberOnly1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNumberOnly1KeyPressed(evt);
            }
        });

        jNumberOnly2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNumberOnly2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jNumberOnly2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNumberOnly2KeyPressed(evt);
            }
        });

        jNumberOnly3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNumberOnly3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jNumberOnly3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNumberOnly3KeyPressed(evt);
            }
        });

        jNumberOnly4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNumberOnly4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jNumberOnly4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNumberOnly4KeyPressed(evt);
            }
        });

        jNumberOnly5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNumberOnly5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jNumberOnly5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNumberOnly5KeyPressed(evt);
            }
        });

        jNumberOnly6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNumberOnly6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jNumberOnly6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNumberOnly6KeyPressed(evt);
            }
        });

        jNumberOnly7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNumberOnly7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jNumberOnly7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNumberOnly7KeyPressed(evt);
            }
        });

        jNumberOnly8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNumberOnly8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jNumberOnly8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNumberOnly8KeyPressed(evt);
            }
        });

        jNumberOnly9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNumberOnly9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jNumberOnly9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNumberOnly9KeyPressed(evt);
            }
        });

        jlableF20.setText("Catatan Pelanggan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbuttonF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbuttonF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbuttonF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlableF23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlableF20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jlableF24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JDTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jlableF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlableF7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlableF33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlableF8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlableF34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jlableF13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlableF12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlableF11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlableF14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlableF15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlableF16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlableF17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlableF18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlableF19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jNumberOnly1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jNumberOnly2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jNumberOnly3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jNumberOnly4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jNumberOnly5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jNumberOnly6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jNumberOnly7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jNumberOnly8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jNumberOnly9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlableF9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlableF35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTNamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlableF10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlableF36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlableF35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTNamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlableF36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlableF23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlableF24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JDTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlableF33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlableF34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlableF11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNumberOnly1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNumberOnly2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNumberOnly3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNumberOnly4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNumberOnly5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNumberOnly6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNumberOnly7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNumberOnly8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableF19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNumberOnly9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlableF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlableF20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF1ActionPerformed
        tambahData(false);
    }//GEN-LAST:event_jbuttonF1ActionPerformed

    private void jbuttonF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF2ActionPerformed
        tambahData(true);
    }//GEN-LAST:event_jbuttonF2ActionPerformed

    private void jbuttonF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF4ActionPerformed
        dispose();
    }//GEN-LAST:event_jbuttonF4ActionPerformed

    private void jbuttonF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF3ActionPerformed
        ubahData();
    }//GEN-LAST:event_jbuttonF3ActionPerformed

    private void JDTanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JDTanggalPropertyChange

    }//GEN-LAST:event_JDTanggalPropertyChange

    private void JDTanggalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JDTanggalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JTNamaPelanggan.requestFocus();
        }
    }//GEN-LAST:event_JDTanggalKeyPressed

    private void JTACatatanPelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTACatatanPelangganKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (IdEdit == null) {
                tambahData(false);
            } else {
                ubahData();
            }
        }
    }//GEN-LAST:event_JTACatatanPelangganKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (IdEdit == null) {
            GlobalVar.Var.tambahPengujianBahanBaku = null;
        } else {
            GlobalVar.Var.ubahPengujianBahanBaku = null;
        }
    }//GEN-LAST:event_formWindowClosed

    private void JTNamaPelangganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTNamaPelangganKeyReleased

    }//GEN-LAST:event_JTNamaPelangganKeyReleased

    private void JTNamaPelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTNamaPelangganKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jNumberOnly1.requestFocus();
        }
    }//GEN-LAST:event_JTNamaPelangganKeyPressed

    private void jScrollPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jbuttonF1.isVisible()) {
                tambahData(false);
            } else {
                ubahData();
            }
        }
    }//GEN-LAST:event_jScrollPane1KeyPressed

    private void JTNamaPerusahaanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTNamaPerusahaanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JTAlamat.requestFocus();
        }
    }//GEN-LAST:event_JTNamaPerusahaanKeyPressed

    private void JTNamaPerusahaanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTNamaPerusahaanKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNamaPerusahaanKeyReleased

    private void JTAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTAlamatKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTAlamatKeyPressed

    private void JTAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTAlamatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JTAlamatKeyReleased

    private void jNumberOnly1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNumberOnly1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jNumberOnly2.requestFocus();
        }
    }//GEN-LAST:event_jNumberOnly1KeyPressed

    private void jNumberOnly2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNumberOnly2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jNumberOnly3.requestFocus();
        }
    }//GEN-LAST:event_jNumberOnly2KeyPressed

    private void jNumberOnly3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNumberOnly3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jNumberOnly4.requestFocus();
        }
    }//GEN-LAST:event_jNumberOnly3KeyPressed

    private void jNumberOnly4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNumberOnly4KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jNumberOnly5.requestFocus();
        }
    }//GEN-LAST:event_jNumberOnly4KeyPressed

    private void jNumberOnly5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNumberOnly5KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jNumberOnly6.requestFocus();
        }
    }//GEN-LAST:event_jNumberOnly5KeyPressed

    private void jNumberOnly6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNumberOnly6KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jNumberOnly7.requestFocus();
        }
    }//GEN-LAST:event_jNumberOnly6KeyPressed

    private void jNumberOnly7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNumberOnly7KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jNumberOnly8.requestFocus();
        }
    }//GEN-LAST:event_jNumberOnly7KeyPressed

    private void jNumberOnly8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNumberOnly8KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jNumberOnly9.requestFocus();
        }
    }//GEN-LAST:event_jNumberOnly8KeyPressed

    private void jNumberOnly9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNumberOnly9KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JTACatatanPelanggan.requestFocus();
        }
    }//GEN-LAST:event_jNumberOnly9KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SurveyKepuasanPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SurveyKepuasanPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SurveyKepuasanPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SurveyKepuasanPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SurveyKepuasanPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static KomponenGUI.JdateCF JDTanggal;
    private KomponenGUI.JTextAreaF JTACatatanPelanggan;
    private KomponenGUI.JtextF JTAlamat;
    private KomponenGUI.JtextF JTNamaPelanggan;
    private KomponenGUI.JtextF JTNamaPerusahaan;
    private KomponenGUI.JNumberOnly jNumberOnly1;
    private KomponenGUI.JNumberOnly jNumberOnly2;
    private KomponenGUI.JNumberOnly jNumberOnly3;
    private KomponenGUI.JNumberOnly jNumberOnly4;
    private KomponenGUI.JNumberOnly jNumberOnly5;
    private KomponenGUI.JNumberOnly jNumberOnly6;
    private KomponenGUI.JNumberOnly jNumberOnly7;
    private KomponenGUI.JNumberOnly jNumberOnly8;
    private KomponenGUI.JNumberOnly jNumberOnly9;
    private javax.swing.JScrollPane jScrollPane1;
    private KomponenGUI.JbuttonF jbuttonF1;
    private KomponenGUI.JbuttonF jbuttonF2;
    private KomponenGUI.JbuttonF jbuttonF3;
    private KomponenGUI.JbuttonF jbuttonF4;
    private KomponenGUI.JlableF jlableF10;
    private KomponenGUI.JlableF jlableF11;
    private KomponenGUI.JlableF jlableF12;
    private KomponenGUI.JlableF jlableF13;
    private KomponenGUI.JlableF jlableF14;
    private KomponenGUI.JlableF jlableF15;
    private KomponenGUI.JlableF jlableF16;
    private KomponenGUI.JlableF jlableF17;
    private KomponenGUI.JlableF jlableF18;
    private KomponenGUI.JlableF jlableF19;
    private KomponenGUI.JlableF jlableF20;
    private KomponenGUI.JlableF jlableF23;
    private KomponenGUI.JlableF jlableF24;
    private KomponenGUI.JlableF jlableF33;
    private KomponenGUI.JlableF jlableF34;
    private KomponenGUI.JlableF jlableF35;
    private KomponenGUI.JlableF jlableF36;
    private KomponenGUI.JlableF jlableF6;
    private KomponenGUI.JlableF jlableF7;
    private KomponenGUI.JlableF jlableF8;
    private KomponenGUI.JlableF jlableF9;
    // End of variables declaration//GEN-END:variables

    void tambahData(Boolean tutup) {
        if (checkInput()) {
            Insert insert = new Insert();
            Boolean berhasil = false;
            berhasil = insert.simpan("INSERT INTO `snitbsurveykepuasanpelanggan`(`NamaPerusahaan`, `Alamat`, `Tanggal`, `NamaPelanggan`, `Nilai`, `CatatanDariPelanggan`) VALUES ('" + JTNamaPerusahaan.getText() + "','" + JTAlamat.getText() + "','" + FDateF.datetostr(JDTanggal.getDate(), "yyyy-MM-dd") + "','" + JTNamaPelanggan.getText() + "', '" + getNilai() + "','" + JTACatatanPelanggan.getText() + "')", "Survey Kepuasan Pelanggan", this);
            if (berhasil) {
                if (listSurveyKepuasanPelanggan != null) {
                    listSurveyKepuasanPelanggan.load();
                }
                if (tutup) {
                    dispose();
                } else {
                    JTNamaPerusahaan.setText("");
                    JTAlamat.setText("");
                    JTNamaPelanggan.setText("");
                    jNumberOnly1.setText("0");
                    jNumberOnly2.setText("0");
                    jNumberOnly3.setText("0");
                    jNumberOnly4.setText("0");
                    jNumberOnly5.setText("0");
                    jNumberOnly6.setText("0");
                    jNumberOnly7.setText("0");
                    jNumberOnly8.setText("0");
                    jNumberOnly9.setText("0");
                    JTACatatanPelanggan.setText("");
                }
            }
        }
    }

    void ubahData() {
        if (checkInput()) {
            Update update = new Update();
            Boolean berhasil = false;
            berhasil = update.Ubah("UPDATE `snitbsurveykepuasanpelanggan` SET `NamaPerusahaan`='" + JTNamaPerusahaan.getText() + "',`Alamat`='" + JTAlamat.getText() + "',`Tanggal`='" + FDateF.datetostr(JDTanggal.getDate(), "yyyy-MM-dd") + "',`NamaPelanggan`='" + JTNamaPelanggan.getText() + "',`Nilai`='" + getNilai() + "',`CatatanDariPelanggan`='" + JTACatatanPelanggan.getText() + "' WHERE `IdSurveyKepuasanPelanggan` = " + IdEdit, "Survey Kepuasan Pelanggan", this);
            if (listSurveyKepuasanPelanggan != null) {
                listSurveyKepuasanPelanggan.load();
            }
            if (berhasil) {
                dispose();
            }
        }
    }

}
